name: EventMirror
main: me.asofold.bpl.eventmirror.EventMirror
version: ${version}-b${BUILD_NUMBER}
commands:
  eventmirror:
    usage: "/<command> To toggle receiving event mirror messages."
    aliases: [mirror]